[[characters]]
name = "james"
ids = [256, 257]

[[characters]]
name = "maria"
ids = [270]
reference_animation_offset = 475136

[mappings]
# from.to
# value = from bone, index = to bone
# value of -1 means there is no corresponding bone on the from character
james.maria = [
    0,  # 0
    1,  # 1
    2,  # 2
    4,  # 3
    3,  # 4
    5,  # 5
    8,  # 6
    6,  # 7
    7,  # 8
    15, # 9
    13, # 10
    9,  # 11
    -1, # 12
    -1, # 13
    -1, # 14
    14, # 15
    10, # 16
    -1, # 17
    -1, # 18
    -1, # 19
    25, # 20
    27, # 21
    26, # 22
    28, # 23
    29, # 24
    31, # 25
    30, # 26
    32, # 27
    33, # 28
    34, # 29
    40, # 30
    -1, # 31
    35, # 32
    -1, # 33
    -1, # 34
    -1, # 35
]

maria.james = [
    0,  # 0
    1,  # 1
    2,  # 2
    4,  # 3
    3,  # 4
    5,  # 5
    7,  # 6
    8,  # 7
    6,  # 8
    11, # 9
    16, # 10
    -1, # 11
    -1, # 12
    10, # 13
    15, # 14
    9,  # 15
    -1, # 16
    -1, # 17
    -1, # 18
    -1, # 19
    -1, # 20
    -1, # 21
    -1, # 22
    -1, # 23
    -1, # 24
    20, # 25
    22, # 26
    21, # 27
    23, # 28
    24, # 29
    26, # 30
    25, # 31
    27, # 32
    28, # 33
    29, # 34
    32, # 35
    -1, # 36
    -1, # 37
    -1, # 38
    -1, # 39
    30, # 40
]