[[characters]]
name = "james"
ids = [256, 257]

[[characters]]
name = "maria"
ids = [270]
reference_animation_offset = 475136

[mappings]
# from.to
# value = from bone, index = to bone
# value of -1 means there is no corresponding bone on the from character
james.maria = [
    0,  # 0
    1,  # 1
    2,  # 2
    4,  # 3
    3,  # 4
    5,  # 5
    8,  # 6
    6,  # 7
    7,  # 8
    15, # 9
    13, # 10
    9,  # 11
    -1, # 12
    -1, # 13
    -1, # 14
    14, # 15
    10, # 16
    -1, # 17
    -1, # 18
    -1, # 19
    25, # 20
    27, # 21
    26, # 22
    28, # 23
    29, # 24
    31, # 25
    30, # 26
    32, # 27
    33, # 28
    34, # 29
    40, # 30
    -1, # 31
    35, # 32
    -1, # 33
    -1, # 34
    -1, # 35
]